apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zlic-rcoric1
  name: 'counter-frontend'
spec:
  selector:
    matchLabels:
      app: counter-frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: counter-frontend
    spec:
      containers:
        - name: counter-frontend
          image: ghcr.io/rcoric3/counter-frontend:v1
          ports:
            - containerPort: 3000
          env:
           - name: npm_config_cache
             value: ./.npm-cache
           - name: NODE_ENV
             value: production
           - name: REACT_APP_BACKEND_URL
             valueFrom:
              configMapKeyRef:
                name: counter-config
                key: backendurl
